### PR TITLE
Check if device is still connected before sending disconnect

### LINKED ISSUE #20: Device incorrectly marked as away when switching between radios
Last night, my phone was incorrectly marked as away while it still was connected to the WiFi. Further inspection of the logs revealed the following sequence of events:
* My phone connects to the 5 GHz radio (`wlan1`)
* `push_event.sh` gets notified and tells Home Assistant that I'm home
* A bit later, my phone disconnects from the 2.4 GHz radio (`wlan0`)
* `push_event.sh` gets notified and incorrectly tells Home Assistant that I'm away

Relevant log fragment:
```
Sat Dec 29 04:48:57 2018 daemon.info hostapd: wlan1: STA AA:BB:CC:DD:EE:FF IEEE 802.11: authenticated
Sat Dec 29 04:48:57 2018 daemon.info hostapd: wlan1: STA AA:BB:CC:DD:EE:FF IEEE 802.11: associated (aid 1)
Sat Dec 29 04:48:57 2018 daemon.notice hostapd: wlan1: AP-STA-CONNECTED AA:BB:CC:DD:EE:FF
Sat Dec 29 04:48:57 2018 daemon.info hostapd: wlan1: STA AA:BB:CC:DD:EE:FF WPA: pairwise key handshake completed (RSN)
Sat Dec 29 04:48:57 2018 user.debug /usr/lib/hass/push_event.sh: push_event wlan1 AP-STA-CONNECTED AA:BB:CC:DD:EE:FF
Sat Dec 29 04:48:57 2018 user.debug /usr/lib/hass/push_event.sh: build_payload AA:BB:CC:DD:EE:FF OnePlus_6.lan 86400
Sat Dec 29 04:48:57 2018 user.debug /usr/lib/hass/push_event.sh: post {"mac":"AA:BB:CC:DD:EE:FF","host_name":"OnePlus_6.lan","consider_home":"86400","source_type":"router"}
Sat Dec 29 04:48:57 2018 user.debug /usr/lib/hass/push_event.sh: post response []
Sat Dec 29 04:53:58 2018 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED AA:BB:CC:DD:EE:FF
Sat Dec 29 04:53:58 2018 daemon.info hostapd: wlan0: STA AA:BB:CC:DD:EE:FF IEEE 802.11: disassociated due to inactivity
Sat Dec 29 04:53:58 2018 user.debug /usr/lib/hass/push_event.sh: push_event wlan0 AP-STA-DISCONNECTED AA:BB:CC:DD:EE:FF
Sat Dec 29 04:53:58 2018 user.debug /usr/lib/hass/push_event.sh: build_payload AA:BB:CC:DD:EE:FF OnePlus_6.lan 20
Sat Dec 29 04:53:59 2018 user.debug /usr/lib/hass/push_event.sh: post {"mac":"AA:BB:CC:DD:EE:FF","host_name":"OnePlus_6.lan","consider_home":"20","source_type":"router"}
Sat Dec 29 04:53:59 2018 user.debug /usr/lib/hass/push_event.sh: post response []
Sat Dec 29 04:53:59 2018 daemon.info hostapd: wlan0: STA AA:BB:CC:DD:EE:FF IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
```

I think the best solution is to check if the device is still connected to any radio (comparable to what's done in `sync_state`) before sending the disconnect check.

### PR DESCRIPTION
**Pull request by oxan**
Proposed fix for #20.

### CODE REVIEW

**Comment by mueslo** [comment]
Instead of the for loop you could just grep for the mac address directly

**Comment by mueslo** [comment]
Thanks!

**Comment by ties** [comment]
This patch seems to cause issues in my multi-station/multi-radio setup. From remote syslog:
```
Jan  8 10:40:54 station1 hostapd: wlan1: AP-STA-DISCONNECTED 84:de:ad:be:ef:00
Jan  8 10:40:54 station1 hostapd: wlan1: STA 84:de:ad:be:ef:00 IEEE 802.11: disassociated due to inactivity                                                                        
Jan  8 10:40:54 station1 /usr/lib/hass/push_event.sh: push_event wlan1 AP-STA-DISCONNECTED 84:de:ad:be:ef:00                                                                       
Jan  8 10:40:54 station1 /usr/lib/hass/push_event.sh: push_event ignored as device is still online                                                                                 
Jan  8 10:40:55 station1 hostapd: wlan1: STA 84:de:ad:be:ef:00 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)                                                
...
Jan  8 11:00:00 station1 /etc/config/hass.sh: sync_state
Jan  8 11:00:00 station1 /etc/config/hass.sh: build_payload 80:de:ad:be:ef:00  24:00 station1                                                                                       
Jan  8 11:00:00 station1 /etc/config/hass.sh: build_payload e4:de:ad:be:ef:01  24:00 station1   
```

I think the same behavior was experienced by @oxan reported in #20. I will investigate the behavior when this patch is removed (and reduce `timeout_conn`to +- the cron interval) to prevent devices from staying online by accident.

**Comment by oxan** [comment]
Yes, I also experienced this behaviour. I'm currently testing commit oxan/openwrt_hass_devicetracker@5ebd171, which at least so far has not shown this behaviour. However, even then `sync_state` is still broken so it's not a complete fix.

**Pull request merged**
